{% set version = "1.1.2" %}
{% set build_number = 0 %}

package:
  name: ipydrawio-build
  version: {{ version }}

source:
  - folder: ipydrawio
    url: https://pypi.io/packages/source/i/ipydrawio/ipydrawio-{{ version }}.tar.gz
    sha256: f199f03893cd071687bc6fabc7a6201a9c831c28a723af0f703587e926bb8965

  - folder: ipydrawio-export
    url: https://pypi.io/packages/source/i/ipydrawio-export/ipydrawio-export-{{ version }}.tar.gz
    sha256: b780a5fd4e5678f20f5e687d1e75c169534383f59fbaede5c96c3b20d0cb6c24

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo "tests in outputs"

outputs:
  - name: ipydrawio
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd ipydrawio && {{ PYTHON }} -m pip install . -vv --no-deps
      entry_points:
        - jupyter-ipydrawio = ipydrawio.app:main
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - ipywidgets >=7.6
        - jupyterlab ==3.*
        - jupyterlab_widgets >=1
        - lxml
        - python >=3.6
    test:
      imports:
        - ipydrawio
      requires:
        - pip
        - pytest-console-scripts
        - pytest-cov
      commands:
        - pip check
        - jupyter ipydrawio --version
        - jupyter ipydrawio --help
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "@deathbeds/ipydrawio.*OK"  # [unix]
        - cat labextensions | grep -ie "@deathbeds/ipydrawio-webpack .*OK"  # [unix]
        - cat labextensions | grep -ie "@deathbeds/ipydrawio-notebook .*OK"  # [unix]
        - cat labextensions | grep -ie "@deathbeds/ipydrawio-jupyter-templates .*OK"  # [unix]
        - pytest -vv --pyargs ipydrawio --cov=ipydrawio --cov-fail-under=100 --cov-report=term-missing:skip-covered
    about:
      home: https://github.com/deathbeds/ipydrawio
      summary: Draw.io Diagrams as Jupyter Widgets
      license: Apache-2.0
      doc_url: https://ipydrawio.rtfd.io
      doc_source_url: https://github.com/deathbeds/ipydrawio/tree/v{{ version }}/docs
      license_file:
        - ipydrawio/LICENSE.txt
        - ipydrawio/src/ipydrawio/ext/ipd/static/third-party-licenses.json
        - ipydrawio/src/ipydrawio/ext/ipdnb/static/third-party-licenses.json
        - ipydrawio/src/ipydrawio/ext/ipdwp/static/third-party-licenses.json
        - ipydrawio/src/ipydrawio/ext/ipjt/static/third-party-licenses.json


  - name: ipydrawio-export
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd ipydrawio-export && {{ PYTHON }} -m pip install . -vv --no-deps
      entry_points:
      - jupyter-ipydrawio-export = ipydrawio_export.app:main
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - ipydrawio =={{ version }}.*
        - lxml
        - nodejs >=12
        - pillow
        - pypdf2
        - python >=3.6
        - requests_cache
    test:
      imports:
        - ipydrawio_export
      requires:
        - pip
        - pytest-cov
        - pytest-tornasync
        - pytest-console-scripts
      commands:
        - pip check
        - jupyter ipydrawio-export --version
        - jupyter ipydrawio-export --help
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "@deathbeds/ipydrawio-pdf.*OK"  # [unix]
        - jupyter serverextension list
        - jupyter serverextension list 1>serverextensions 2>&1
        - cat serverextensions | grep "ipydrawio_export.*OK"  # [unix]
        {% set pytest_args = "--cov-fail-under=96" %}
        # TODO: investigate potential docker/locale issues upstream to restore coverage
        {% set pytest_args = "--cov-fail-under=54 -k 'not (export_empty or export_merged or serverextension_export)'" %}  # [linux]
        - pytest -vv {{ pytest_args }} --pyargs ipydrawio_export --script-launch-mode=subprocess --cov=ipydrawio_export --cov-report=term-missing:skip-covered
    about:
      home: https://github.com/deathbeds/ipydrawio
      summary: PDF export for IPyDrawio
      license: Apache-2.0
      doc_url: https://ipydrawio.rtfd.io
      doc_source_url: https://github.com/deathbeds/ipydrawio/tree/v{{ version }}/
      license_file:
      - ipydrawio-export/LICENSE.txt
      - ipydrawio-export/src/ipydrawio_export/ext/ipdpdf/static/third-party-licenses.json

about:
  home: https://github.com/deathbeds/ipydrawio
  summary: Draw.io Diagrams as Jupyter Widgets
  license: Apache-2.0
  license_file: ipydrawio/LICENSE.txt
  doc_url: https://ipydrawio.rtfd.io
  doc_source_url: https://github.com/deathbeds/ipydrawio/tree/v{{ version }}/docs

extra:
  feedstock-name: ipydrawio
  recipe-maintainers:
    - bollwyvl
