{% set version = "1.2.2" %}
{% set build_number = 0 %}

package:
  name: ipydrawio-build
  version: {{ version }}

source:
  - folder: ipydrawio
    url: https://pypi.io/packages/source/i/ipydrawio/ipydrawio-{{ version }}.tar.gz
    sha256: c2b99d501e21676d51ebd73fc11ef8a29d6a7736756686d69f55dc4a5430b0aa

  - folder: ipydrawio-export
    url: https://pypi.io/packages/source/i/ipydrawio-export/ipydrawio-export-{{ version }}.tar.gz
    sha256: 61df9c9ede657d6626c4cff06d00f7ab513fdd58c66f96b5e0253fc688e50858

  - folder: ipydrawio-widgets
    url: https://pypi.io/packages/source/i/ipydrawio-widgets/ipydrawio-widgets-{{ version }}.tar.gz
    sha256: bc9195c0739e3f1f0ec0b4806232b8fa1ef0c32f8bc4e168de0c858f502e21f2

  - folder: ipydrawio-mathjax
    url: https://pypi.io/packages/source/i/ipydrawio-mathjax/ipydrawio-mathjax-{{ version }}.tar.gz
    sha256: 003a9bcab9636876e7b3d20c935162aa301d6669beb07e6665f76b1454363b22

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  commands:
    - echo "tests in outputs"

outputs:
  - name: ipydrawio-widgets
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd ipydrawio-widgets && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - ipywidgets >=7.6,<9
        - python >=3.7
    test:
      source_files:
        - ipydrawio-widgets/tests
      imports:
        - ipydrawio_widgets
      requires:
        - pip
        - pytest
      commands:
        - pip check
        - pytest -vv ipydrawio-widgets/tests
    about:
      home: https://github.com/deathbeds/ipydrawio
      summary: Draw.io Diagrams as Jupyter Widgets (kernel only)
      license: Apache-2.0
      license_file: ipydrawio-widgets/LICENSE.txt

  - name: ipydrawio
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd ipydrawio && {{ PYTHON }} -m pip install . -vv --no-deps
      entry_points:
        - jupyter-ipydrawio = ipydrawio.app:main
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - {{ pin_subpackage("ipydrawio-widgets", exact=True) }}
        - jupyterlab ==3.*
        - jupyterlab_widgets >=1
        - lxml
        - python >=3.7
    test:
      source_files:
        - ipydrawio/tests
      imports:
        - ipydrawio
      requires:
        - pip
        - pytest-console-scripts
        - m2-grep  # [win]
      commands:
        - pip check
        - jupyter ipydrawio --version
        - jupyter ipydrawio --help
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - grep -iE "@deathbeds/ipydrawio.*OK" labextensions
        - grep -iE "@deathbeds/ipydrawio-webpack .*OK" labextensions
        - grep -iE "@deathbeds/ipydrawio-notebook .*OK" labextensions
        - grep -iE "@deathbeds/ipydrawio-jupyter-templates .*OK" labextensions
        - pytest -vv ipydrawio/tests
    about:
      home: https://github.com/deathbeds/ipydrawio
      summary: Draw.io Diagrams as Jupyter Widgets
      license: Apache-2.0
      doc_url: https://ipydrawio.rtfd.io
      doc_source_url: https://github.com/deathbeds/ipydrawio/tree/v{{ version }}/docs
      license_file:
        - ipydrawio/LICENSE.txt
        - ipydrawio/_/ipydrawio/static/third-party-licenses.json
        - ipydrawio/_/ipydrawio-notebook/static/third-party-licenses.json
        - ipydrawio/_/ipydrawio-webpack/static/third-party-licenses.json
        - ipydrawio/_/ipydrawio-jupyter-templates/static/third-party-licenses.json

  - name: ipydrawio-export
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd ipydrawio-export && {{ PYTHON }} -m pip install . -vv --no-deps
      entry_points:
      - jupyter-ipydrawio-export = ipydrawio_export.app:main
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - {{ pin_subpackage("ipydrawio", exact=True) }}
        - lxml
        - nodejs >=12,!=13,!=15,!=17
        - pillow
        - pypdf2
        - python >=3.7
        - requests_cache
    test:
      source_files:
        - ipydrawio-export/tests
      imports:
        - ipydrawio_export
      requires:
        - pip
        - pytest-tornasync
        - pytest-console-scripts
        - m2-grep  # [win]
      commands:
        - pip check
        - jupyter ipydrawio-export --version
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - jupyter serverextension list
        - jupyter serverextension list 1>serverextensions 2>&1
        - grep -iE "@deathbeds/ipydrawio-pdf.*OK" labextensions
        - grep -iE "ipydrawio_export .*OK" serverextensions
        - pytest -vv --script-launch-mode=subprocess ipydrawio-export/tests || pytest -vv --script-launch-mode=subprocess ipydrawio-export/tests
    about:
      home: https://github.com/deathbeds/ipydrawio
      summary: PDF export for IPyDrawio
      license: Apache-2.0
      doc_url: https://ipydrawio.rtfd.io
      doc_source_url: https://github.com/deathbeds/ipydrawio/tree/v{{ version }}/
      license_file:
      - ipydrawio-export/LICENSE.txt
      - ipydrawio-export/_/ipydrawio-pdf/static/third-party-licenses.json

  - name: ipydrawio-mathjax
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd ipydrawio-mathjax && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - {{ pin_subpackage("ipydrawio", max_pin="x.x.x") }}
        - python >=3.7
    test:
      source_files:
        - ipydrawio-mathjax/tests
      imports:
        - ipydrawio_mathjax
      requires:
        - m2-grep  # [win]
        - pip
        - pytest
      commands:
        - pip check
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - grep -iE "@deathbeds/ipydrawio-mathjax .*OK" labextensions
        - pytest -vv ipydrawio-mathjax/tests
    about:
      home: https://github.com/deathbeds/ipydrawio
      summary: MathJax for ipydrawio
      license: Apache-2.0
      license_file:
        - ipydrawio-mathjax/LICENSE.txt
        - ipydrawio-mathjax/_/ipydrawio-mathjax/static/third-party-licenses.json

about:
  home: https://github.com/deathbeds/ipydrawio
  summary: Draw.io Diagrams as Jupyter Widgets
  license: Apache-2.0
  license_file: ipydrawio/LICENSE.txt
  doc_url: https://ipydrawio.rtfd.io
  doc_source_url: https://github.com/deathbeds/ipydrawio/tree/v{{ version }}/docs

extra:
  feedstock-name: ipydrawio
  recipe-maintainers:
    - bollwyvl
